#!/usr/bin/env python3
"""Validate and optionally exercise the two-service Render deployment."""

from __future__ import annotations

import argparse
import os
import shutil
import socket
import subprocess
import sys
import tempfile
import time
import urllib.error
import urllib.request
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
BLUEPRINT = ROOT / "render.yaml"

EXPECTED = {
    "signal-desk-mcp": {
        "buildCommand": "pip install --require-hashes --requirement mcp_server/requirements.lock",
        "startCommand": "python mcp_server/stock_research_mcp_server.py",
        "healthCheckPath": "/health",
        "lock": ROOT / "mcp_server" / "requirements.lock",
        "imports": "fastmcp,databricks.sdk,jwt,psycopg2",
    },
    "signal-desk-frontend": {
        "buildCommand": "pip install --require-hashes --requirement dashboard/requirements.lock",
        "startCommand": (
            "gunicorn --chdir dashboard --pythonpath .. --bind 0.0.0.0:$PORT "
            "--workers 2 --threads 4 --timeout 60 app:app"
        ),
        "healthCheckPath": "/healthz",
        "lock": ROOT / "dashboard" / "requirements.lock",
        "imports": "flask,gunicorn,authlib,databricks.sql,fastmcp,jwt,psycopg2",
    },
}

REQUIRED_SECRETS = {
    "LAKEBASE_URL",
    "DATA_WORKSPACE_CLIENT_ID",
    "DATA_WORKSPACE_CLIENT_SECRET",
    "FRONTEND_ASSERTION_PUBLIC_KEY",
    "MCP_SUPERVISOR_TOKEN",
    "OIDC_CLIENT_SECRET",
    "FLASK_SESSION_SECRET",
    "FRONTEND_ASSERTION_PRIVATE_KEY",
}


def _services() -> dict[str, dict]:
    document = yaml.safe_load(BLUEPRINT.read_text())
    services = document.get("services") if isinstance(document, dict) else None
    if not isinstance(services, list):
        raise AssertionError("render.yaml must contain a services list")
    return {service["name"]: service for service in services}


def validate_blueprint() -> None:
    services = _services()
    if set(services) != set(EXPECTED):
        raise AssertionError(f"expected exactly {sorted(EXPECTED)}, got {sorted(services)}")
    seen_secrets: set[str] = set()
    for name, expected in EXPECTED.items():
        service = services[name]
        for key in ("buildCommand", "startCommand", "healthCheckPath"):
            if service.get(key) != expected[key]:
                raise AssertionError(f"{name}.{key} does not match the accepted deployment contract")
        if service.get("type") != "web" or service.get("runtime") != "python" or service.get("plan") != "free":
            raise AssertionError(f"{name} must be a Python web service on the development free plan")
        for variable in service.get("envVars", []):
            if variable.get("sync") is False:
                if "value" in variable:
                    raise AssertionError(f"secret {variable['key']} must not contain a literal value")
                seen_secrets.add(variable["key"])
    missing = REQUIRED_SECRETS - seen_secrets
    if missing:
        raise AssertionError(f"missing sync:false secret declarations: {sorted(missing)}")
    frontend_values = {
        variable["key"]: variable.get("value") for variable in services["signal-desk-frontend"].get("envVars", [])
    }
    if frontend_values.get("OIDC_ISSUER_URL") != "https://accounts.google.com":
        raise AssertionError("frontend must use the accepted Google OIDC issuer")
    if frontend_values.get("OIDC_REDIRECT_URI") != "https://signal-desk-frontend-s88i.onrender.com/oidc/callback":
        raise AssertionError("frontend OIDC callback must match the reserved Render service name")
    lowered = BLUEPRINT.read_text().lower()
    if "postgresql://" in lowered or "dapi" in lowered:
        raise AssertionError("render.yaml contains a prohibited credential-like literal")


def validate_locks() -> None:
    for name, expected in EXPECTED.items():
        lock = expected["lock"]
        text = lock.read_text()
        if "autogenerated by uv" not in text or "--python-platform x86_64-unknown-linux-gnu" not in text:
            raise AssertionError(f"{lock.relative_to(ROOT)} is not the expected Linux uv lock")
        if "--hash=sha256:" not in text:
            raise AssertionError(f"{lock.relative_to(ROOT)} does not enforce package hashes")
        if "https://" in text or "http://" in text:
            raise AssertionError(f"{lock.relative_to(ROOT)} contains an unexpected direct URL")
        if name == "signal-desk-mcp" and "fastmcp==" not in text:
            raise AssertionError("MCP lock omits FastMCP")
        if name == "signal-desk-frontend" and "gunicorn==" not in text:
            raise AssertionError("frontend lock omits Gunicorn")


def clean_install() -> None:
    uv = shutil.which("uv")
    if not uv:
        raise RuntimeError("uv is required for clean-install verification")
    with tempfile.TemporaryDirectory(prefix="signal-desk-render-") as temporary:
        base = Path(temporary)
        for name, expected in EXPECTED.items():
            environment = base / name
            subprocess.run([uv, "venv", "--python", "3.11", str(environment)], check=True)
            python = environment / "bin" / "python"
            subprocess.run(
                [uv, "pip", "sync", "--require-hashes", "--python", str(python), str(expected["lock"])],
                check=True,
            )
            imports = ";".join(f"import {module}" for module in expected["imports"].split(","))
            subprocess.run([str(python), "-c", imports], cwd=ROOT, check=True)


def _free_port() -> int:
    with socket.socket() as listener:
        listener.bind(("127.0.0.1", 0))
        return int(listener.getsockname()[1])


def _wait_for_health(port: int, path: str, process: subprocess.Popen[str]) -> None:
    url = f"http://127.0.0.1:{port}{path}"
    deadline = time.monotonic() + 20
    while time.monotonic() < deadline:
        if process.poll() is not None:
            stdout, _ = process.communicate()
            raise RuntimeError(f"service exited before health check:\n{stdout[-4000:]}")
        try:
            with urllib.request.urlopen(url, timeout=1) as response:  # noqa: S310 - local smoke endpoint
                if response.status == 200:
                    return
        except (urllib.error.URLError, TimeoutError):
            time.sleep(0.2)
    raise RuntimeError(f"timed out waiting for {url}")


def process_smoke() -> None:
    services = _services()
    for name, expected in EXPECTED.items():
        port = _free_port()
        command = services[name]["startCommand"].replace("$PORT", str(port))
        environment = os.environ.copy()
        environment.update(
            {variable["key"]: str(variable["value"]) for variable in services[name]["envVars"] if "value" in variable}
        )
        environment.update({"PATH": f"{Path(sys.executable).parent}:{environment['PATH']}", "PORT": str(port)})
        if name == "signal-desk-mcp":
            environment["SIGNAL_DESK_RUN_MIGRATIONS"] = "false"
        else:
            environment.update({"SIGNAL_DESK_HOSTING": "local", "SIGNAL_DESK_IDENTITY_MODE": "header"})
        process = subprocess.Popen(
            command,
            cwd=ROOT,
            env=environment,
            shell=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
        )
        try:
            _wait_for_health(port, expected["healthCheckPath"], process)
        finally:
            process.terminate()
            try:
                process.wait(timeout=5)
            except subprocess.TimeoutExpired:
                process.kill()
                process.wait(timeout=5)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--clean-install", action="store_true", help="install both hash-pinned locks in fresh venvs")
    parser.add_argument("--process-smoke", action="store_true", help="start both exact Blueprint commands and probe health")
    args = parser.parse_args()
    validate_blueprint()
    validate_locks()
    if args.clean_install:
        clean_install()
    if args.process_smoke:
        process_smoke()
    print("Render reproducibility checks passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
